# Generated by Django 2.0.10 on 2019-01-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=200, null=True)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('student_birthdate', models.CharField(blank=True, max_length=200, null=True)),
                ('student_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('student_leader', models.CharField(blank=True, max_length=200, null=True)),
                ('student_contactleader', models.CharField(blank=True, max_length=200, null=True)),
                ('student_network', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
